package net.mem_memov.copsoq3.format

import net.mem_memov.copsoq3.Format
import net.mem_memov.copsoq3.QuestionEnumeration

object Testograf extends Format:

  override val columnOffset: Int = 22

  override val rowOffset: Int = 1

  override def getColumnNumber(questionEnumeration: QuestionEnumeration): Option[Int] =

    questionEnumeration match {
      case QuestionEnumeration.QuantitativeDemands1 => None
      case QuestionEnumeration.QuantitativeDemands2 => None
      case QuestionEnumeration.QuantitativeDemands3 => None
      case QuestionEnumeration.QuantitativeDemands4 => None
      case QuestionEnumeration.WorkPace1 => Some(24)
      case QuestionEnumeration.WorkPace2 => None
      case QuestionEnumeration.WorkPace3 => None
      case QuestionEnumeration.EmotionalDemands1 => None
      case QuestionEnumeration.EmotionalDemands2 => None
      case QuestionEnumeration.EmotionalDemands3 => None
      case QuestionEnumeration.DemandsForHidingEmotions1 => None
      case QuestionEnumeration.DemandsForHidingEmotions2 => None
      case QuestionEnumeration.DemandsForHidingEmotions3 => None
      case QuestionEnumeration.DemandsForHidingEmotions4 => None
      case QuestionEnumeration.InfluenceAtWork1 => None
      case QuestionEnumeration.InfluenceAtWork2 => None
      case QuestionEnumeration.InfluenceAtWork3 => None
      case QuestionEnumeration.InfluenceAtWork4 => None
      case QuestionEnumeration.InfluenceAtWork5 => None
      case QuestionEnumeration.InfluenceAtWork6 => None
      case QuestionEnumeration.PossibilitiesForDevelopment2 => None
      case QuestionEnumeration.PossibilitiesForDevelopment3 => None
      case QuestionEnumeration.PossibilitiesForDevelopment4 => None
      case QuestionEnumeration.VariationOfWork1 => None
      case QuestionEnumeration.VariationOfWork2 => None
      case QuestionEnumeration.ControlOverWorkingTime1 => None
      case QuestionEnumeration.ControlOverWorkingTime2 => None
      case QuestionEnumeration.ControlOverWorkingTime3 => None
      case QuestionEnumeration.ControlOverWorkingTime4 => None
      case QuestionEnumeration.ControlOverWorkingTime5 => None
      case QuestionEnumeration.MeaningOfWork1 => None
      case QuestionEnumeration.MeaningOfWork2 => None
      case QuestionEnumeration.Predictability1 => None
      case QuestionEnumeration.Predictability2 => None
      case QuestionEnumeration.Recognition1 => None
      case QuestionEnumeration.Recognition2 => None
      case QuestionEnumeration.Recognition3 => None
      case QuestionEnumeration.RoleClarity1 => None
      case QuestionEnumeration.RoleClarity2 => None
      case QuestionEnumeration.RoleClarity3 => None
      case QuestionEnumeration.RoleConflicts2 => None
      case QuestionEnumeration.RoleConflicts3 => None
      case QuestionEnumeration.IllegitimateTasks1 => None
      case QuestionEnumeration.QualityOfLeadership1 => None
      case QuestionEnumeration.QualityOfLeadership2 => None
      case QuestionEnumeration.QualityOfLeadership3 => None
      case QuestionEnumeration.QualityOfLeadership4 => None
      case QuestionEnumeration.SocialSupportFromSupervisor1 => None
      case QuestionEnumeration.SocialSupportFromSupervisor2 => None
      case QuestionEnumeration.SocialSupportFromSupervisor3 => None
      case QuestionEnumeration.SocialSupportFromColleagues1 => None
      case QuestionEnumeration.SocialSupportFromColleagues2 => None
      case QuestionEnumeration.SocialSupportFromColleagues3 => None
      case QuestionEnumeration.SenseOfCommunityAtWork1 => None
      case QuestionEnumeration.SenseOfCommunityAtWork2 => None
      case QuestionEnumeration.SenseOfCommunityAtWork3 => None
      case QuestionEnumeration.CommitmentToTheWorkplace1 => None
      case QuestionEnumeration.CommitmentToTheWorkplace2 => None
      case QuestionEnumeration.CommitmentToTheWorkplace3 => None
      case QuestionEnumeration.CommitmentToTheWorkplace4 => None
      case QuestionEnumeration.CommitmentToTheWorkplace5 => None
      case QuestionEnumeration.WorkEngagement1 => None
      case QuestionEnumeration.WorkEngagement2 => None
      case QuestionEnumeration.WorkEngagement3 => None
      case QuestionEnumeration.JobInsecurity1 => None
      case QuestionEnumeration.JobInsecurity2 => None
      case QuestionEnumeration.JobInsecurity3 => None
      case QuestionEnumeration.InsecurityOverWorkingConditions1 => None
      case QuestionEnumeration.InsecurityOverWorkingConditions2 => None
      case QuestionEnumeration.InsecurityOverWorkingConditions3 => None
      case QuestionEnumeration.InsecurityOverWorkingConditions4 => None
      case QuestionEnumeration.InsecurityOverWorkingConditions5 => None
      case QuestionEnumeration.QualityOfWork1 => None
      case QuestionEnumeration.QualityOfWork2 => None
      case QuestionEnumeration.JobSatisfaction1 => None
      case QuestionEnumeration.JobSatisfaction2 => None
      case QuestionEnumeration.JobSatisfaction3 => None
      case QuestionEnumeration.JobSatisfaction4 => None
      case QuestionEnumeration.JobSatisfaction5 => None
      case QuestionEnumeration.WorkLifeConflict1 => None
      case QuestionEnumeration.WorkLifeConflict2 => None
      case QuestionEnumeration.WorkLifeConflict3 => None
      case QuestionEnumeration.WorkLifeConflict5 => None
      case QuestionEnumeration.WorkLifeConflict6 => None
      case QuestionEnumeration.HorizontalTrust1 => None
      case QuestionEnumeration.HorizontalTrust2 => None
      case QuestionEnumeration.HorizontalTrust3 => None
      case QuestionEnumeration.VerticalTrust1 => None
      case QuestionEnumeration.VerticalTrust2 => None
      case QuestionEnumeration.VerticalTrust3 => None
      case QuestionEnumeration.VerticalTrust4 => None
      case QuestionEnumeration.OrganizationalJustice1 => None
      case QuestionEnumeration.OrganizationalJustice2 => None
      case QuestionEnumeration.OrganizationalJustice3 => None
      case QuestionEnumeration.OrganizationalJustice4 => None
      case QuestionEnumeration.GossipAndSlander1 => None
      case QuestionEnumeration.GossipAndSlander2 => None
      case QuestionEnumeration.ConflictsAndQuarrels1 => None
      case QuestionEnumeration.UnpleasantTeasing1 => None
      case QuestionEnumeration.UnpleasantTeasing2 => None
      case QuestionEnumeration.CyberBullying1 => None
      case QuestionEnumeration.CyberBullying2 => None
      case QuestionEnumeration.SexualHarassment1 => None
      case QuestionEnumeration.SexualHarassment2 => None
      case QuestionEnumeration.ThreatsOfViolence1 => None
      case QuestionEnumeration.ThreatsOfViolence2 => None
      case QuestionEnumeration.PhysicalViolence1 => None
      case QuestionEnumeration.PhysicalViolence2 => None
      case QuestionEnumeration.Bullying1 => None
      case QuestionEnumeration.Bullying2 => None
      case QuestionEnumeration.Bullying3 => None
      case QuestionEnumeration.SelfRatedHealth1 => None
      case QuestionEnumeration.SelfRatedHealth2 => None
      case QuestionEnumeration.SleepingTroubles1 => None
      case QuestionEnumeration.SleepingTroubles2 => None
      case QuestionEnumeration.SleepingTroubles3 => None
      case QuestionEnumeration.SleepingTroubles4 => None
      case QuestionEnumeration.Burnout1 => None
      case QuestionEnumeration.Burnout2 => None
      case QuestionEnumeration.Burnout3 => None
      case QuestionEnumeration.Burnout4 => None
      case QuestionEnumeration.Stress1 => None
      case QuestionEnumeration.Stress2 => None
      case QuestionEnumeration.Stress3 => None
      case QuestionEnumeration.SomaticStress1 => None
      case QuestionEnumeration.SomaticStress2 => None
      case QuestionEnumeration.SomaticStress3 => None
      case QuestionEnumeration.SomaticStress4 => None
      case QuestionEnumeration.CognitiveStress1 => None
      case QuestionEnumeration.CognitiveStress2 => None
      case QuestionEnumeration.CognitiveStress3 => None
      case QuestionEnumeration.CognitiveStress4 => None
      case QuestionEnumeration.DepressiveSymptoms1 => None
      case QuestionEnumeration.DepressiveSymptoms2 => None
      case QuestionEnumeration.DepressiveSymptoms3 => None
      case QuestionEnumeration.DepressiveSymptoms4 => None
      case QuestionEnumeration.SelfEfficacy1 => None
      case QuestionEnumeration.SelfEfficacy2 => None
      case QuestionEnumeration.SelfEfficacy3 => None
      case QuestionEnumeration.SelfEfficacy4 => None
      case QuestionEnumeration.SelfEfficacy5 => None
      case QuestionEnumeration.SelfEfficacy6 => None
    }


