package net.mem_memov.copsoq3.format

import net.mem_memov.copsoq3.Format
import net.mem_memov.copsoq3.QuestionEnumeration

object Testograf extends Format:

  override val columnOffset: Int = 22

  override val rowOffset: Int = 1

  override def getColumnNumber(questionEnumeration: QuestionEnumeration): Option[Int] =

    questionEnumeration match {
      case QuestionEnumeration.QuantitativeDemands1 => Some(25)
      case QuestionEnumeration.QuantitativeDemands2 => Some(24)
      case QuestionEnumeration.QuantitativeDemands3 => Some(26)
      case QuestionEnumeration.QuantitativeDemands4 => None
      case QuestionEnumeration.WorkPace1 => Some(22)
      case QuestionEnumeration.WorkPace2 => Some(23)
      case QuestionEnumeration.WorkPace3 => None
      case QuestionEnumeration.CognitiveDemands1 => None
      case QuestionEnumeration.CognitiveDemands2 => Some(29)
      case QuestionEnumeration.CognitiveDemands3 => None
      case QuestionEnumeration.CognitiveDemands4 => None
      case QuestionEnumeration.EmotionalDemands1 => Some(31)
      case QuestionEnumeration.EmotionalDemands2 => Some(28)
      case QuestionEnumeration.EmotionalDemands3 => Some(32)
      case QuestionEnumeration.DemandsForHidingEmotions1 => None
      case QuestionEnumeration.DemandsForHidingEmotions2 => Some(33)
      case QuestionEnumeration.DemandsForHidingEmotions3 => None
      case QuestionEnumeration.DemandsForHidingEmotions4 => Some(30)
      case QuestionEnumeration.InfluenceAtWork1 => Some(39)
      case QuestionEnumeration.InfluenceAtWork2 => None
      case QuestionEnumeration.InfluenceAtWork3 => Some(40)
      case QuestionEnumeration.InfluenceAtWork4 => None
      case QuestionEnumeration.InfluenceAtWork5 => None
      case QuestionEnumeration.InfluenceAtWork6 => None
      case QuestionEnumeration.PossibilitiesForDevelopment2 => Some(45)
      case QuestionEnumeration.PossibilitiesForDevelopment3 => Some(46)
      case QuestionEnumeration.PossibilitiesForDevelopment4 => None
      case QuestionEnumeration.VariationOfWork1 => Some(44)
      case QuestionEnumeration.VariationOfWork2 => None
      case QuestionEnumeration.ControlOverWorkingTime1 => Some(41)
      case QuestionEnumeration.ControlOverWorkingTime2 => Some(42)
      case QuestionEnumeration.ControlOverWorkingTime3 => Some(69)
      case QuestionEnumeration.ControlOverWorkingTime4 => Some(43)
      case QuestionEnumeration.ControlOverWorkingTime5 => Some(27)
      case QuestionEnumeration.MeaningOfWork1 => Some(48)
      case QuestionEnumeration.MeaningOfWork2 => Some(47)
      case QuestionEnumeration.Predictability1 => Some(51)
      case QuestionEnumeration.Predictability2 => Some(52)
      case QuestionEnumeration.Recognition1 => Some(80)
      case QuestionEnumeration.Recognition2 => Some(79)
      case QuestionEnumeration.Recognition3 => None
      case QuestionEnumeration.RoleClarity1 => Some(53)
      case QuestionEnumeration.RoleClarity2 => Some(54)
      case QuestionEnumeration.RoleClarity3 => Some(55)
      case QuestionEnumeration.RoleConflicts2 => Some(56)
      case QuestionEnumeration.RoleConflicts3 => Some(57)
      case QuestionEnumeration.IllegitimateTasks1 => Some(58)
      case QuestionEnumeration.QualityOfLeadership1 => Some(59)
      case QuestionEnumeration.QualityOfLeadership2 => Some(60)
      case QuestionEnumeration.QualityOfLeadership3 => Some(61)
      case QuestionEnumeration.QualityOfLeadership4 => Some(62)
      case QuestionEnumeration.SocialSupportFromSupervisor1 => Some(66)
      case QuestionEnumeration.SocialSupportFromSupervisor2 => Some(65)
      case QuestionEnumeration.SocialSupportFromSupervisor3 => Some(67)
      case QuestionEnumeration.SocialSupportFromColleagues1 => Some(63)
      case QuestionEnumeration.SocialSupportFromColleagues2 => Some(64)
      case QuestionEnumeration.SocialSupportFromColleagues3 => Some(68)
      case QuestionEnumeration.SenseOfCommunityAtWork1 => Some(70)
      case QuestionEnumeration.SenseOfCommunityAtWork2 => Some(71)
      case QuestionEnumeration.SenseOfCommunityAtWork3 => None
      case QuestionEnumeration.CommitmentToTheWorkplace1 => Some(50)
      case QuestionEnumeration.CommitmentToTheWorkplace2 => None
      case QuestionEnumeration.CommitmentToTheWorkplace3 => None
      case QuestionEnumeration.CommitmentToTheWorkplace4 => Some(87)
      case QuestionEnumeration.CommitmentToTheWorkplace5 => Some(49)
      case QuestionEnumeration.WorkEngagement1 => Some(97)
      case QuestionEnumeration.WorkEngagement2 => Some(98)
      case QuestionEnumeration.WorkEngagement3 => Some(99)
      case QuestionEnumeration.JobInsecurity1 => Some(81)
      case QuestionEnumeration.JobInsecurity2 => Some(82)
      case QuestionEnumeration.JobInsecurity3 => Some(83)
      case QuestionEnumeration.InsecurityOverWorkingConditions1 => Some(84)
      case QuestionEnumeration.InsecurityOverWorkingConditions2 => None
      case QuestionEnumeration.InsecurityOverWorkingConditions3 => Some(85)
      case QuestionEnumeration.InsecurityOverWorkingConditions4 => Some(86)
      case QuestionEnumeration.InsecurityOverWorkingConditions5 => None
      case QuestionEnumeration.QualityOfWork1 => None
      case QuestionEnumeration.QualityOfWork2 => None
      case QuestionEnumeration.JobSatisfaction1 => Some(88)
      case QuestionEnumeration.JobSatisfaction2 => Some(89)
      case QuestionEnumeration.JobSatisfaction3 => Some(90)
      case QuestionEnumeration.JobSatisfaction4 => Some(92)
      case QuestionEnumeration.JobSatisfaction5 => Some(91)
      case QuestionEnumeration.WorkLifeConflict1 => Some(38)
      case QuestionEnumeration.WorkLifeConflict2 => Some(36)
      case QuestionEnumeration.WorkLifeConflict3 => Some(37)
      case QuestionEnumeration.WorkLifeConflict5 => Some(34)
      case QuestionEnumeration.WorkLifeConflict6 => Some(35)
      case QuestionEnumeration.HorizontalTrust1 => None
      case QuestionEnumeration.HorizontalTrust2 => None
      case QuestionEnumeration.HorizontalTrust3 => Some(74)
      case QuestionEnumeration.VerticalTrust1 => Some(75)
      case QuestionEnumeration.VerticalTrust2 => Some(76)
      case QuestionEnumeration.VerticalTrust3 => None
      case QuestionEnumeration.VerticalTrust4 => None
      case QuestionEnumeration.OrganizationalJustice1 => Some(77)
      case QuestionEnumeration.OrganizationalJustice2 => None
      case QuestionEnumeration.OrganizationalJustice3 => None
      case QuestionEnumeration.OrganizationalJustice4 => Some(78)
      case QuestionEnumeration.GossipAndSlander1 => None
      case QuestionEnumeration.GossipAndSlander2 => None
      case QuestionEnumeration.ConflictsAndQuarrels1 => Some(73)
      case QuestionEnumeration.UnpleasantTeasing1 => None
      case QuestionEnumeration.UnpleasantTeasing2 => None
      case QuestionEnumeration.CyberBullying1 => None
      case QuestionEnumeration.CyberBullying2 => None
      case QuestionEnumeration.SexualHarassment1 => None
      case QuestionEnumeration.SexualHarassment2 => None
      case QuestionEnumeration.ThreatsOfViolence1 => None
      case QuestionEnumeration.ThreatsOfViolence2 => None
      case QuestionEnumeration.PhysicalViolence1 => None
      case QuestionEnumeration.PhysicalViolence2 => None
      case QuestionEnumeration.Bullying1 => None
      case QuestionEnumeration.Bullying2 => Some(72)
      case QuestionEnumeration.Bullying3 => None
      case QuestionEnumeration.SelfRatedHealth1 => Some(93)
      case QuestionEnumeration.SelfRatedHealth2 => None
      case QuestionEnumeration.SleepingTroubles1 => None
      case QuestionEnumeration.SleepingTroubles2 => None
      case QuestionEnumeration.SleepingTroubles3 => None
      case QuestionEnumeration.SleepingTroubles4 => None
      case QuestionEnumeration.Burnout1 => Some(96)
      case QuestionEnumeration.Burnout2 => Some(94)
      case QuestionEnumeration.Burnout3 => Some(95)
      case QuestionEnumeration.Burnout4 => None
      case QuestionEnumeration.Stress1 => None
      case QuestionEnumeration.Stress2 => None
      case QuestionEnumeration.Stress3 => None
      case QuestionEnumeration.SomaticStress1 => None
      case QuestionEnumeration.SomaticStress2 => None
      case QuestionEnumeration.SomaticStress3 => None
      case QuestionEnumeration.SomaticStress4 => None
      case QuestionEnumeration.CognitiveStress1 => None
      case QuestionEnumeration.CognitiveStress2 => None
      case QuestionEnumeration.CognitiveStress3 => None
      case QuestionEnumeration.CognitiveStress4 => None
      case QuestionEnumeration.DepressiveSymptoms1 => None
      case QuestionEnumeration.DepressiveSymptoms2 => None
      case QuestionEnumeration.DepressiveSymptoms3 => None
      case QuestionEnumeration.DepressiveSymptoms4 => None
      case QuestionEnumeration.SelfEfficacy1 => None
      case QuestionEnumeration.SelfEfficacy2 => None
      case QuestionEnumeration.SelfEfficacy3 => None
      case QuestionEnumeration.SelfEfficacy4 => None
      case QuestionEnumeration.SelfEfficacy5 => None
      case QuestionEnumeration.SelfEfficacy6 => None
    }


